baseurl = "http://www.ericcarlisle.com/"
languageCode = "en-us"
title = "Flexible, Powerful Static Website Creation With Hugo"
googleAnalytics = "UA-123-45"
Paginate = 1

[taxonomies]
slide = "slides"
genre = "genres"

[[menu.ssg]]
    name = "About SSGs"
    url = "/static-site-generators/"
    pre= ""
[[menu.ssg]]
    name = "Intro to Hugo"
    url = "/hugo/"
    pre= ""
[[menu.content]]
    name = "Movies"
    url = "/movie/"
    pre= ""

